name: .NET Core

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/AzureFunctions.SqlBinding.sln
    - name: Build
      run: dotnet build ./src/AzureFunctions.SqlBinding.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
